# Translations template for keystone.
# Copyright (C) 2014 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-09-07 06:06+0000\n"
"PO-Revision-Date: 2014-06-20 20:11+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Korean (Korea) (http://www.transifex.com/projects/p/keystone/"
"language/ko_KR/)\n"
"Language: ko_KR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: keystone/notifications.py:176
#, python-format
msgid "Method not callable: %s"
msgstr ""

#: keystone/catalog/core.py:56
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr ""

#: keystone/catalog/core.py:61
#, python-format
msgid ""
"Malformed endpoint '%(url)s'. The following type error occurred during "
"string substitution: %(typeerror)s"
msgstr ""

#: keystone/catalog/core.py:67
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type notifier ?)"
msgstr ""

#: keystone/common/openssl.py:90
#, python-format
msgid "Command %(to_exec)s exited with %(retcode)s- %(output)s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:100
#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr ""

#: keystone/contrib/endpoint_policy/core.py:129
#: keystone/contrib/endpoint_policy/core.py:228
#, python-format
msgid ""
"Circular reference or a repeated entry found in region tree - %(region_id)s."
msgstr ""

#: keystone/contrib/federation/idp.py:404
#, python-format
msgid "Error when signing assertion, reason: %(reason)s"
msgstr ""

#: keystone/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "기존 예외가 삭제됨: %s"

#: keystone/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "예기치 않은 예외 %d 번 발생하였습니다... 다시 시도중."

#: keystone/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "고정 기간 루프 호출에서"

#: keystone/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "동적 루프 호출에서"

#: keystone/openstack/common/policy.py:508
#, python-format
msgid "Failed to understand rule %s"
msgstr "%s 규칙을 이해하는데 실패했습니다"

#: keystone/openstack/common/policy.py:518
#, python-format
msgid "No handler for matches of kind %s"
msgstr "%s 유형의 일치에 대한 핸들러가 없음"

#: keystone/openstack/common/policy.py:788
#, python-format
msgid "Failed to understand rule %r"
msgstr "룰 %r를 이해하지 못했습니다."

#: keystone/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr ""

#: keystone/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "처리되지 않은 예외"
